{% set version = "1.3.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-vroom
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/vroom_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/vroom/vroom_{{ version }}.tar.gz
  sha256: dcd2261d91653526b751a48f920a9f297db53d67ef2413c792b8f3ebeeae82f0

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bit64
    - r-cpp11 >=0.2.0
    - r-crayon
    - r-glue
    - r-hms
    - r-lifecycle
    - r-progress >=1.2.1
    - r-rlang >=0.4.2
    - r-tibble >=2.0.0
    - r-tidyselect
    - r-vctrs
    - r-withr
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-bit64
    - r-cpp11 >=0.2.0
    - r-crayon
    - r-glue
    - r-hms
    - r-lifecycle
    - r-progress >=1.2.1
    - r-rlang >=0.4.2
    - r-tibble >=2.0.0
    - r-tidyselect
    - r-vctrs
    - r-withr

test:
  commands:
    - $R -e "library('vroom')"           # [not win]
    - "\"%R%\" -e \"library('vroom')\""  # [win]

about:
  home: https://github.com/r-lib/vroom
  license: GPL-3.0-only
  summary: The goal of 'vroom' is to read and write data (like 'csv', 'tsv' and 'fwf') quickly. When reading it uses a quick initial indexing step, then reads the values lazily , so only the data you actually use needs to be read.  The writer formats the data in parallel and writes to disk asynchronously from formatting.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - halldc

# Package: vroom
# Title: Read and Write Rectangular Text Data Quickly
# Version: 1.2.0
# Authors@R: c(person(given = "Jim", family = "Hester", role = c("aut", "cre"), email = "james.f.hester@gmail.com", comment = c(ORCID = "0000-0002-2739-7082")), person(given = "Hadley", family = "Wickham", role = "aut", email = "hadley@rstudio.com", comment = c(ORCID = "0000-0003-4757-117X")), person(given = "https://github.com/mandreyel/", role = "cph", comment = "mio library"), person(given = "R Core Team", role = "ctb", comment = "localtime.c code adapted from R"), person(given = "Jukka", family = "Jylanki", role = "cph", comment = "grisu3 implementation"), person(given = "Mikkel", family = "Jrgensen", role = "cph", comment = "grisu3 implementation"), person(given = "RStudio", role = c("cph", "fnd")))
# Description: The goal of 'vroom' is to read and write data (like 'csv', 'tsv' and 'fwf') quickly. When reading it uses a quick initial indexing step, then reads the values lazily , so only the data you actually use needs to be read.  The writer formats the data in parallel and writes to disk asynchronously from formatting.
# License: GPL-3
# URL: https://github.com/r-lib/vroom
# BugReports: https://github.com/r-lib/vroom/issues
# Depends: R (>= 3.1)
# Imports: bit64, crayon, glue, hms, lifecycle, Rcpp (>= 0.12.18.3), rlang (>= 0.4.2), tibble (>= 2.0.0), tidyselect, withr
# Suggests: bench (>= 1.1.0), covr, curl, dplyr, forcats, fs, ggplot2, knitr, patchwork, prettyunits, purrr, readr (>= 1.3.1), rmarkdown, rstudioapi, scales, spelling, testthat, tidyr, xml2
# LinkingTo: progress (>= 1.2.1), Rcpp
# VignetteBuilder: knitr
# Copyright: file COPYRIGHTS
# Encoding: UTF-8
# Language: en-US
# LazyData: true
# RoxygenNote: 7.0.2
# SystemRequirements: C++11
# NeedsCompilation: yes
# Packaged: 2020-01-13 21:00:57 UTC; jhester
# Author: Jim Hester [aut, cre] (<https://orcid.org/0000-0002-2739-7082>), Hadley Wickham [aut] (<https://orcid.org/0000-0003-4757-117X>), https://github.com/mandreyel/ [cph] (mio library), R Core Team [ctb] (localtime.c code adapted from R), Jukka Jylanki [cph] (grisu3 implementation), Mikkel Jrgensen [cph] (grisu3 implementation), RStudio [cph, fnd]
# Maintainer: Jim Hester <james.f.hester@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-01-13 22:40:02 UTC
