{% set version = "1.6.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-vroom
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/vroom_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/vroom/vroom_{{ version }}.tar.gz
  sha256: eb0e33d53212f9c7e8b38d632c98bd5015365cc13f55dadb15ff0d404b31807c

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-cpp11                    # [build_platform != target_platform]
    - r-progress                 # [build_platform != target_platform]
    - r-crayon                   # [build_platform != target_platform]
    - r-cli                      # [build_platform != target_platform]
    - r-lifecycle                # [build_platform != target_platform]
    - r-tibble                   # [build_platform != target_platform]
    - r-tidyselect               # [build_platform != target_platform]
    - r-vctrs                    # [build_platform != target_platform]
    - r-hms                      # [build_platform != target_platform]
    - r-rlang                    # [build_platform != target_platform]
    - r-tzdb                     # [build_platform != target_platform]
    - r-bit64                    # [build_platform != target_platform]
    - r-glue                     # [build_platform != target_platform]
    - r-withr                    # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bit64
    - r-cli
    - r-cpp11 >=0.2.0
    - r-crayon
    - r-glue
    - r-hms
    - r-lifecycle
    - r-progress >=1.2.1
    - r-rlang >=0.4.2
    - r-tibble >=2.0.0
    - r-tidyselect
    - r-tzdb >=0.1.1
    - r-vctrs >=0.2.0
    - r-withr
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-bit64
    - r-cli
    - r-cpp11 >=0.2.0
    - r-crayon
    - r-glue
    - r-hms
    - r-lifecycle
    - r-progress >=1.2.1
    - r-rlang >=0.4.2
    - r-tibble >=2.0.0
    - r-tidyselect
    - r-tzdb >=0.1.1
    - r-vctrs >=0.2.0
    - r-withr

test:
  commands:
    - $R -e "library('vroom')"           # [not win]
    - "\"%R%\" -e \"library('vroom')\""  # [win]

about:
  home: https://github.com/r-lib/vroom
  license: MIT
  summary: The goal of 'vroom' is to read and write data (like 'csv', 'tsv' and 'fwf') quickly. When reading it uses a quick initial indexing step, then reads the values lazily , so only the data you actually use needs to be read.  The writer formats the data in parallel and writes to disk asynchronously from formatting.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - halldc
